FROM python:3.12-slim

WORKDIR /app

# Sistem bağımlılıkları
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Python bağımlılıkları
COPY pyproject.toml .
RUN pip install --upgrade pip setuptools wheel && \
    pip install -e .[dev,backend]

COPY . .

EXPOSE 8000
